{
 "title": "ESP DHT Sensor",
 "description": "Dashboard for ESP DHT Sensor Using Zabbix API ",
 "tags": [ "iot" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "Sensor",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "options": {
    "content": "<center><img src=\"https://www.pngmart.com/files/21/Internet-Of-Things-PNG-Isolated-File.png\" width=\"203\" height=\"203\"></center>\r\n"
   },
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(<time_column>) as time_sec,\n  <value column> as value,\n  <series name column> as metric\nFROM <table name>\nWHERE $__timeFilter(time_column)\nORDER BY <time_column> ASC\n"
    }
   ]
  },
  {
   "title": "Temperatura",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "Ambient Sensor" },
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "" }
     ],
     "group": { "filter": "HEAA/IOT Devices" },
     "host": { "filter": "$Sensor" },
     "item": { "filter": "Sensor 1 - Temperature" },
     "itemTag": { "filter": "" },
     "method": "GET",
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Umidade do Ar",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "Ambient Sensor" },
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "" }
     ],
     "group": { "filter": "HEAA/IOT Devices" },
     "host": { "filter": "$Sensor" },
     "item": { "filter": "Sensor 1 - Humidity" },
     "itemTag": { "filter": "" },
     "method": "GET",
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Local de Instalação ",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 11, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "application": { "filter": "Hardware Information" },
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "" }
     ],
     "group": { "filter": "HEAA/IOT Devices" },
     "host": { "filter": "$Sensor" },
     "item": { "filter": "Hardware location" },
     "itemTag": { "filter": "" },
     "method": "GET",
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Rede Conectada",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "application": { "filter": "Connection Information" },
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "" }
     ],
     "group": { "filter": "HEAA/IOT Devices" },
     "host": { "filter": "$Sensor" },
     "item": { "filter": "Wifi Connected SSID" },
     "itemTag": { "filter": "" },
     "method": "GET",
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Tempo do ar Ligado",
   "type": "stat",
   "description": "Tempo em que o Ar está ligado\nA troca é feita a cada 24 horas.",
   "gridPos": { "h": 4, "w": 3, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "application": { "filter": "Timer" },
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "" }
     ],
     "group": { "filter": "HEAA/IOT Devices" },
     "host": { "filter": "$Sensor" },
     "item": { "filter": "Hardware Time Counter" },
     "itemTag": { "filter": "" },
     "method": "GET",
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Tempo p/ próxima Inversão",
   "type": "stat",
   "description": "Tempo Para a próxima Inversão\nA troca é feita a cada 24 horas.",
   "gridPos": { "h": 4, "w": 3, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "application": { "filter": "Timer" },
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "" }
     ],
     "group": { "filter": "HEAA/IOT Devices" },
     "host": { "filter": "$Sensor" },
     "item": { "filter": "Hardware Time Regressive" },
     "itemTag": { "filter": "" },
     "method": "GET",
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "yesoreyeram-boomtheme-panel",
   "gridPos": { "h": 1, "w": 1, "x": 23, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(<time_column>) as time_sec,\n  <value column> as value,\n  <series name column> as metric\nFROM <table name>\nWHERE $__timeFilter(time_column)\nORDER BY <time_column> ASC\n"
    }
   ]
  },
  {
   "title": "ID do Sensor",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 17, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "application": { "filter": "Hardware Information" },
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "" }
     ],
     "group": { "filter": "HEAA/IOT Devices" },
     "host": { "filter": "$Sensor" },
     "item": { "filter": "Hardware ID" },
     "itemTag": { "filter": "" },
     "method": "GET",
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Sensor Trim",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 20, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "application": { "filter": "Ambient Sensor" },
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "" }
     ],
     "group": { "filter": "HEAA/IOT Devices" },
     "host": { "filter": "$Sensor" },
     "item": { "filter": "Sensor 1 - Trimmer" },
     "itemTag": { "filter": "" },
     "method": "GET",
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Ar Condicionado 1 ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 11, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "application": { "filter": "Air Conditioning 1" },
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "" }
     ],
     "group": { "filter": "HEAA/IOT Devices" },
     "host": { "filter": "$Sensor" },
     "item": { "filter": "Air Conditioning 1 - Status" },
     "itemTag": { "filter": "" },
     "method": "GET",
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Ar Condicionado 2",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 14, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "application": { "filter": "Air Conditioning 2" },
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "" }
     ],
     "group": { "filter": "HEAA/IOT Devices" },
     "host": { "filter": "$Sensor" },
     "item": { "filter": "Air Conditioning 2 - Status" },
     "itemTag": { "filter": "" },
     "method": "GET",
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Temperatura",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "application": { "filter": "Ambient Sensor" },
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "" }
     ],
     "group": { "filter": "HEAA/IOT Devices" },
     "host": { "filter": "$Sensor" },
     "item": { "filter": "Sensor 1 - Temperature" },
     "itemTag": { "filter": "" },
     "method": "GET",
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "alexanderzobnin-zabbix-triggers-panel",
   "gridPos": { "h": 5, "w": 6, "x": 17, "y": 7 },
   "targets": [
    {
     "application": { "filter": "/.*/" },
     "group": { "filter": "HEAA/IOT Devices" },
     "host": { "filter": "$Sensor" },
     "item": { "filter": "/.*/" },
     "itemTag": { "filter": "" },
     "options": {
      "acknowledged": 2,
      "disableDataAlignment": false,
      "hostProxy": false,
      "hostsInMaintenance": false,
      "limit": 1001,
      "minSeverity": 0,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "sortProblems": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "showProblems": "problems",
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": " Funcionamento",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 11, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "application": { "filter": "Air Conditioning 1" },
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "" }
     ],
     "group": { "filter": "HEAA/IOT Devices" },
     "host": { "filter": "$Sensor" },
     "item": { "filter": "Air Conditioning 1 - Error" },
     "itemTag": { "filter": "" },
     "method": "GET",
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": " Funcionamento",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 14, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "application": { "filter": "Air Conditioning 2" },
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "" }
     ],
     "group": { "filter": "HEAA/IOT Devices" },
     "host": { "filter": "$Sensor" },
     "item": { "filter": "Air Conditioning 2 - Error" },
     "itemTag": { "filter": "" },
     "method": "GET",
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "PING",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "application": { "filter": "Status" },
     "group": { "filter": "HEAA/IOT Devices" },
     "host": { "filter": "$Sensor" },
     "item": { "filter": "ICMP response time" },
     "itemTag": { "filter": "" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Wifi Signal Quality",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "application": { "filter": "Connection Information" },
     "group": { "filter": "HEAA/IOT Devices" },
     "host": { "filter": "$Sensor" },
     "item": { "filter": "Singal Quality" },
     "itemTag": { "filter": "" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Wifi Signal RSSI",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 14, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "targets": [
    {
     "application": { "filter": "Connection Information" },
     "group": { "filter": "HEAA/IOT Devices" },
     "host": { "filter": "$Sensor" },
     "item": { "filter": "Wifi Signal Strength" },
     "itemTag": { "filter": "" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Status Map",
   "type": "state-timeline",
   "gridPos": { "h": 11, "w": 23, "x": 0, "y": 22 },
   "targets": [
    {
     "application": { "filter": "Air Conditioning 1" },
     "functions": [
      {
       "$$hashKey": "object:274",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "$__zbx_item" ],
       "text": "setAlias($__zbx_item)"
      },
      {
       "$$hashKey": "object:275",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAliasByRegex",
        "params": [
         { "name": "aliasByRegex", "type": "string" }
        ]
       },
       "params": [ "^.*[0-9]" ],
       "text": "setAliasByRegex(^.*[0-9])"
      }
     ],
     "group": { "filter": "HEAA/IOT Devices" },
     "host": { "filter": "$Sensor" },
     "item": { "filter": "Air Conditioning 1 - Status" },
     "itemTag": { "filter": "" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Air Conditioning 2" },
     "functions": [
      {
       "$$hashKey": "object:297",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "$__zbx_item" ],
       "text": "setAlias($__zbx_item)"
      },
      {
       "$$hashKey": "object:298",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAliasByRegex",
        "params": [
         { "name": "aliasByRegex", "type": "string" }
        ]
       },
       "params": [ "^.*[0-9]" ],
       "text": "setAliasByRegex(^.*[0-9])"
      }
     ],
     "group": { "filter": "HEAA/IOT Devices" },
     "host": { "filter": "$Sensor" },
     "item": { "filter": "Air Conditioning 2 - Status" },
     "itemTag": { "filter": "" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  }
 ]
}